CREATE DATABASE mouse;
use mouse;

CREATE TABLE plant_info (
    plant_id INT NOT NULL UNIQUE,
    plant_name VARCHAR(50) NOT NULL UNIQUE,
    botanical_name VARCHAR(50) NOT NULL UNIQUE,
    family VARCHAR(30) NOT NULL,
    habitat VARCHAR(50) NOT NULL,
    medicinal_use VARCHAR(100),
    lifespan VARCHAR(20),
    growth_form VARCHAR(30),
    climate VARCHAR(30),
    collected_by VARCHAR(50)
);

INSERT INTO plant_info VALUES
(1, 'Neem', 'Azadirachta indica', 'Meliaceae', 'Tropical', 'Antibacterial', '50+ years', 'Tree', 'Warm', 'Dr. Rao'),
(2, 'Tulsi', 'Ocimum sanctum', 'Lamiaceae', 'Subtropical', 'Immunity booster', '5 years', 'Shrub', 'Humid', 'Dr. Sen'),
(3, 'Aloe Vera', 'Aloe barbadensis', 'Asphodelaceae', 'Arid', 'Skin treatment', '10–12 years', 'Succulent', 'Dry', 'Dr. Khan'),
(4, 'Ashwagandha', 'Withania somnifera', 'Solanaceae', 'Semi-arid', 'Stress relief', '4–5 years', 'Shrub', 'Hot', 'Dr. Iyer'),
(5, 'Mint', 'Mentha arvensis', 'Lamiaceae', 'Wetlands', 'Digestion aid', '1 year', 'Herb', 'Cool', 'Dr. Jaya'),
(6, 'Coriander', 'Coriandrum sativum', 'Apiaceae', 'Cultivated', 'Appetite stimulant', '1 year', 'Herb', 'Temperate', 'Dr. Ravi'),
(7, 'Fenugreek', 'Trigonella foenum-graecum', 'Fabaceae', 'Drylands', 'Diabetes control', '1 year', 'Herb', 'Warm', 'Dr. Patel'),
(8, 'Brahmi', 'Bacopa monnieri', 'Plantaginaceae', 'Marshes', 'Memory enhancer', '3–5 years', 'Creeper', 'Humid', 'Dr. Kaur'),
(9, 'Lemongrass', 'Cymbopogon citratus', 'Poaceae', 'Grasslands', 'Fever reducer', '4 years', 'Grass', 'Tropical', 'Dr. Menon'),
(10, 'Ginger', 'Zingiber officinale', 'Zingiberaceae', 'Humid', 'Anti-inflammatory', '2–3 years', 'Rhizome', 'Tropical', 'Dr. Thomas'),
(11, 'Turmeric', 'Curcuma longa', 'Zingiberaceae', 'Cultivated', 'Antiseptic', '2 years', 'Rhizome', 'Warm', 'Dr. Nair'),
(12, 'Hibiscus', 'Hibiscus rosa-sinensis', 'Malvaceae', 'Tropical', 'Hair tonic', '6–8 years', 'Shrub', 'Humid', 'Dr. Das'),
(13, 'Amalaki', 'Phyllanthus emblica', 'Phyllanthaceae', 'Forests', 'Vitamin C', '25–30 years', 'Tree', 'Moderate', 'Dr. Joshi'),
(14, 'Shatavari', 'Asparagus racemosus', 'Asparagaceae', 'Woodlands', 'Reproductive health', '6–7 years', 'Climber', 'Tropical', 'Dr. Kaul'),
(15, 'Guduchi', 'Tinospora cordifolia', 'Menispermaceae', 'Monsoon forests', 'Immunity booster', '7–10 years', 'Climber', 'Humid', 'Dr. Rathi'),
(16, 'Bael', 'Aegle marmelos', 'Rutaceae', 'Dry forests', 'Digestive aid', '30+ years', 'Tree', 'Hot', 'Dr. Malik'),
(17, 'Senna', 'Senna alexandrina', 'Fabaceae', 'Deserts', 'Laxative', '1 year', 'Shrub', 'Arid', 'Dr. Bhatt'),
(18, 'Kalmegh', 'Andrographis paniculata', 'Acanthaceae', 'Fields', 'Liver tonic', '1–2 years', 'Herb', 'Warm', 'Dr. Roy'),
(19, 'Guggul', 'Commiphora wightii', 'Burseraceae', 'Thorn forests', 'Cholesterol reducer', '20–25 years', 'Shrub', 'Arid', 'Dr. Anand'),
(20, 'Chamomile', 'Matricaria chamomilla', 'Asteraceae', 'Meadows', 'Sleep aid', '1 year', 'Herb', 'Temperate', 'Dr. Sahni'),
(21, 'Lavender', 'Lavandula angustifolia', 'Lamiaceae', 'Hills', 'Aromatherapy', '8–10 years', 'Shrub', 'Cool', 'Dr. Batra'),
(22, 'Eucalyptus', 'Eucalyptus globulus', 'Myrtaceae', 'Forests', 'Respiratory aid', '40+ years', 'Tree', 'Warm', 'Dr. George'),
(23, 'Basil', 'Ocimum basilicum', 'Lamiaceae', 'Tropical', 'Anti-inflammatory', '1–2 years', 'Herb', 'Humid', 'Dr. Raman'),
(24, 'Peppermint', 'Mentha piperita', 'Lamiaceae', 'Riverbanks', 'Coolant', '3 years', 'Herb', 'Moist', 'Dr. Kumar'),
(25, 'Yarrow', 'Achillea millefolium', 'Asteraceae', 'Plains', 'Wound healing', '5 years', 'Herb', 'Temperate', 'Dr. Chauhan'),
(26, 'Marigold', 'Tagetes erecta', 'Asteraceae', 'Gardens', 'Anti-inflammatory', '1 year', 'Herb', 'Warm', 'Dr. Prasad'),
(27, 'Rosemary', 'Salvia rosmarinus', 'Lamiaceae', 'Dry hills', 'Cognitive booster', '10–12 years', 'Shrub', 'Dry', 'Dr. Bhave'),
(28, 'Sage', 'Salvia officinalis', 'Lamiaceae', 'Mediterranean', 'Antioxidant', '4–6 years', 'Shrub', 'Mild', 'Dr. Vyas'),
(29, 'Gotu Kola', 'Centella asiatica', 'Apiaceae', 'Swamps', 'Brain tonic', '3–4 years', 'Herb', 'Humid', 'Dr. Dasgupta'),
(30, 'Licorice', 'Glycyrrhiza glabra', 'Fabaceae', 'Sandy soils', 'Cough relief', '5–7 years', 'Herb', 'Dry', 'Dr. Mehta');


CREATE TABLE food_info (
    food_id INT NOT NULL UNIQUE,
    food_name VARCHAR(50) NOT NULL UNIQUE,
    type VARCHAR(30) NOT NULL,
    origin_country VARCHAR(50),
    calorie INT NOT NULL,
    fat FLOAT,
    protein FLOAT,
    shelf_life INT,
    is_vegan VARCHAR(10),
    registered_by VARCHAR(50)
);

INSERT INTO food_info VALUES
(1, 'Brown Rice', 'Grain', 'India', 370, 3.0, 7.5, 180, 'Yes', 'Analyst A'),
(2, 'Butter', 'Dairy', 'France', 720, 81.0, 0.8, 90, 'No', 'Analyst B'),
(3, 'Tofu', 'Protein', 'China', 145, 4.8, 15.0, 60, 'Yes', 'Analyst C'),
(4, 'Apple', 'Fruit', 'USA', 52, 0.2, 0.3, 30, 'Yes', 'Analyst D'),
(5, 'Cheese', 'Dairy', 'Italy', 402, 33.0, 25.0, 120, 'No', 'Analyst E'),
(6, 'Lentils', 'Pulse', 'India', 116, 0.4, 9.0, 365, 'Yes', 'Analyst F'),
(7, 'Almonds', 'Nut', 'Iran', 579, 50.0, 21.0, 730, 'Yes', 'Analyst G'),
(8, 'Chicken Breast', 'Meat', 'Brazil', 165, 3.6, 31.0, 10, 'No', 'Analyst H'),
(9, 'Salmon', 'Fish', 'Norway', 208, 13.0, 20.0, 7, 'No', 'Analyst I'),
(10, 'Spinach', 'Vegetable', 'USA', 23, 0.4, 2.9, 5, 'Yes', 'Analyst J'),
(11, 'Oats', 'Cereal', 'Germany', 389, 6.9, 16.9, 365, 'Yes', 'Analyst K'),
(12, 'Yogurt', 'Dairy', 'Greece', 59, 0.4, 10.0, 14, 'No', 'Analyst L'),
(13, 'Soy Milk', 'Beverage', 'China', 54, 1.8, 3.3, 30, 'Yes', 'Analyst M'),
(14, 'Quinoa', 'Grain', 'Peru', 120, 1.9, 4.1, 180, 'Yes', 'Analyst N'),
(15, 'Cashews', 'Nut', 'India', 553, 44.0, 18.0, 365, 'Yes', 'Analyst O'),
(16, 'Eggs', 'Poultry', 'USA', 155, 11.0, 13.0, 21, 'No', 'Analyst P'),
(17, 'Broccoli', 'Vegetable', 'Italy', 34, 0.4, 2.8, 7, 'Yes', 'Analyst Q'),
(18, 'Carrots', 'Root', 'Netherlands', 41, 0.2, 0.9, 30, 'Yes', 'Analyst R'),
(19, 'Olive Oil', 'Oil', 'Spain', 884, 100.0, 0.0, 720, 'Yes', 'Analyst S'),
(20, 'Peanut Butter', 'Spread', 'USA', 588, 50.0, 25.0, 365, 'Yes', 'Analyst T'),
(21, 'Banana', 'Fruit', 'Ecuador', 89, 0.3, 1.1, 7, 'Yes', 'Analyst U'),
(22, 'Cottage Cheese', 'Dairy', 'India', 98, 4.3, 11.0, 5, 'No', 'Analyst V'),
(23, 'Mushrooms', 'Fungus', 'Poland', 22, 0.3, 3.1, 10, 'Yes', 'Analyst W'),
(24, 'Cornflakes', 'Cereal', 'UK', 357, 0.4, 7.0, 180, 'Yes', 'Analyst X'),
(25, 'Chickpeas', 'Pulse', 'Turkey', 164, 2.6, 8.9, 365, 'Yes', 'Analyst Y'),
(26, 'Milk', 'Dairy', 'India', 42, 1.0, 3.4, 7, 'No', 'Analyst Z'),
(27, 'Dark Chocolate', 'Snack', 'Belgium', 546, 31.0, 4.9, 365, 'Yes', 'Analyst AA'),
(28, 'Raisins', 'Dry Fruit', 'Iran', 299, 0.5, 3.1, 365, 'Yes', 'Analyst AB'),
(29, 'Dates', 'Dry Fruit', 'Saudi Arabia', 277, 0.2, 1.8, 365, 'Yes', 'Analyst AC'),
(30, 'Green Tea', 'Beverage', 'China', 1, 0.0, 0.1, 730, 'Yes', 'Analyst AD');


CREATE TABLE products_info (
    product_id INT NOT NULL UNIQUE,
    product_name VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL,
    brand VARCHAR(30) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    release_year INT NOT NULL,
    rating FLOAT,
    warranty_years INT,
    available_online VARCHAR(10),
    listed_by VARCHAR(50)
);

INSERT INTO products_info VALUES
(1, 'Smartwatch Alpha', 'Electronics', 'FitTech', 4999.99, 2023, 4.3, 1, 'Yes', 'Seller A'),
(2, 'Eco Bottle', 'Lifestyle', 'HydroFix', 299.00, 2022, 4.7, 2, 'Yes', 'Seller B'),
(3, 'Air Purifier X', 'Appliances', 'AirPure', 8999.00, 2021, 4.5, 3, 'Yes', 'Seller C'),
(4, 'Gaming Mouse', 'Electronics', 'LogiGear', 1599.00, 2023, 4.6, 1, 'Yes', 'Seller D'),
(5, 'Bluetooth Speaker', 'Audio', 'BoomBass', 2599.00, 2020, 4.2, 1, 'Yes', 'Seller E'),
(6, 'LED TV 40"', 'Appliances', 'ViewMax', 20999.00, 2022, 4.4, 2, 'Yes', 'Seller F'),
(7, 'Yoga Mat Pro', 'Fitness', 'FlexiFit', 999.00, 2023, 4.1, 1, 'Yes', 'Seller G'),
(8, 'Wireless Earbuds', 'Audio', 'BeatPod', 3499.00, 2021, 4.3, 1, 'Yes', 'Seller H'),
(9, 'Portable Charger', 'Electronics', 'PowerGo', 799.00, 2023, 4.2, 1, 'Yes', 'Seller I'),
(10, 'Laptop Stand', 'Office', 'WorkEase', 1299.00, 2022, 4.5, 2, 'Yes', 'Seller J'),
(11, 'Smart Bulb', 'Home', 'BrightLite', 699.00, 2021, 4.6, 2, 'Yes', 'Seller K'),
(12, 'Noise Cancelling Headphones', 'Audio', 'ZenSound', 5499.00, 2023, 4.8, 2, 'Yes', 'Seller L'),
(13, 'Fitness Tracker', 'Fitness', 'StepUp', 1999.00, 2020, 4.0, 1, 'Yes', 'Seller M'),
(14, 'Action Camera', 'Photography', 'CamGo', 7999.00, 2022, 4.3, 2, 'Yes', 'Seller N'),
(15, 'Hair Dryer Pro', 'Personal Care', 'StylePro', 1899.00, 2021, 4.2, 2, 'Yes', 'Seller O'),
(16, 'Smart Kettle', 'Home', 'BoilTech', 2499.00, 2023, 4.1, 1, 'Yes', 'Seller P'),
(17, 'Digital Weighing Scale', 'Fitness', 'ScalePro', 1199.00, 2022, 4.3, 2, 'Yes', 'Seller Q'),
(18, 'WiFi Router', 'Networking', 'NetWave', 1599.00, 2020, 4.0, 3, 'Yes', 'Seller R'),
(19, 'Laptop Backpack', 'Lifestyle', 'PackMate', 1899.00, 2021, 4.5, 1, 'Yes', 'Seller S'),
(20, 'Mini Projector', 'Electronics', 'ViewCast', 5999.00, 2023, 4.4, 1, 'Yes', 'Seller T'),
(21, 'Tablet Alpha', 'Electronics', 'TabCore', 14999.00, 2022, 4.2, 2, 'Yes', 'Seller U'),
(22, 'Robot Vacuum', 'Home', 'CleanBot', 17999.00, 2023, 4.6, 2, 'Yes', 'Seller V'),
(23, 'Induction Cooker', 'Kitchen', 'QuickHeat', 2299.00, 2021, 4.1, 1, 'Yes', 'Seller W'),
(24, 'Desk Lamp', 'Office', 'LiteWave', 999.00, 2022, 4.4, 2, 'Yes', 'Seller X'),
(25, 'Coffee Maker', 'Kitchen', 'BrewMaster', 3299.00, 2020, 4.3, 2, 'Yes', 'Seller Y'),
(26, 'Smartphone Y9', 'Electronics', 'Mobix', 18999.00, 2023, 4.5, 1, 'Yes', 'Seller Z'),
(27, 'Keyboard Combo', 'Office', 'KeyMate', 1499.00, 2022, 4.2, 1, 'Yes', 'Seller AA'),
(28, 'Standing Desk', 'Furniture', 'WorkFlex', 11999.00, 2021, 4.7, 5, 'Yes', 'Seller AB'),
(29, 'Monitor 24"', 'Electronics', 'ViewEdge', 8999.00, 2023, 4.4, 3, 'Yes', 'Seller AC'),
(30, 'Smart Thermostat', 'Home', 'HeatWise', 4999.00, 2023, 4.6, 2, 'Yes', 'Seller AD');


CREATE TABLE train_info (
    train_id INT NOT NULL UNIQUE,
    train_name VARCHAR(50) NOT NULL UNIQUE,
    train_type VARCHAR(30),
    source VARCHAR(50) NOT NULL,
    destination VARCHAR(50) NOT NULL,
    distance_km INT NOT NULL,
    avg_speed_kmph FLOAT,
    travel_time_hrs FLOAT,
    running_days VARCHAR(20),
    controller VARCHAR(50)
);

INSERT INTO train_info VALUES
(1, 'Shatabdi Express', 'Superfast', 'Delhi', 'Bhopal', 707, 90.0, 7.8, 'Mon-Sat', 'Officer A'),
(2, 'Rajdhani Express', 'Superfast', 'Mumbai', 'Delhi', 1384, 85.0, 16.5, 'Daily', 'Officer B'),
(3, 'Duronto Express', 'Express', 'Kolkata', 'Secunderabad', 1550, 78.0, 20.7, 'Wed-Sun', 'Officer C'),
(4, 'Garib Rath', 'AC Express', 'Hyderabad', 'Vizag', 689, 70.5, 9.8, 'Tue-Sat', 'Officer D'),
(5, 'Vande Bharat', 'Semi High-Speed', 'Chennai', 'Bangalore', 358, 100.0, 3.5, 'Daily', 'Officer E'),
(6, 'Tejas Express', 'Luxury', 'Mumbai', 'Goa', 579, 85.0, 7.2, 'Fri-Mon', 'Officer F'),
(7, 'Jan Shatabdi', 'Express', 'Ernakulam', 'Trivandrum', 200, 65.0, 3.1, 'Daily', 'Officer G'),
(8, 'Intercity Express', 'Express', 'Mysore', 'Bangalore', 139, 60.0, 2.3, 'Daily', 'Officer H'),
(9, 'Palace on Wheels', 'Luxury', 'Delhi', 'Jaipur', 1240, 50.0, 24.0, 'Weekly', 'Officer I'),
(10, 'Sampoorna Kranti', 'Superfast', 'Patna', 'New Delhi', 1001, 74.0, 13.5, 'Daily', 'Officer J'),
(11, 'Humsafar Express', 'AC Express', 'Bangalore', 'Varanasi', 2335, 60.0, 38.5, 'Mon-Wed', 'Officer K'),
(12, 'Double Decker', 'Express', 'Ahmedabad', 'Mumbai', 491, 80.0, 6.1, 'Daily', 'Officer L'),
(13, 'Antyodaya Express', 'General', 'Darbhanga', 'Delhi', 1180, 58.0, 21.5, 'Alt Days', 'Officer M'),
(14, 'Uday Express', 'Double Decker', 'Coimbatore', 'Bangalore', 400, 76.0, 5.2, 'Mon-Fri', 'Officer N'),
(15, 'Mahamana Express', 'Express', 'Varanasi', 'Delhi', 774, 70.0, 11.0, 'Tue-Sat', 'Officer O'),
(16, 'Yuva Express', 'AC Express', 'Howrah', 'Delhi', 1449, 68.0, 21.3, 'Wed-Sun', 'Officer P'),
(17, 'Deccan Queen', 'Superfast', 'Pune', 'Mumbai', 192, 58.0, 3.2, 'Daily', 'Officer Q'),
(18, 'Mandovi Express', 'Express', 'Mumbai', 'Goa', 581, 65.0, 9.0, 'Daily', 'Officer R'),
(19, 'Goa Express', 'Superfast', 'Goa', 'Delhi', 2165, 55.0, 39.3, 'Mon-Fri', 'Officer S'),
(20, 'Karnataka Express', 'Superfast', 'Bangalore', 'Delhi', 2400, 60.0, 40.0, 'Daily', 'Officer T'),
(21, 'Chennai Express', 'Superfast', 'Chennai', 'Mumbai', 1273, 62.0, 20.5, 'Daily', 'Officer U'),
(22, 'Howrah Mail', 'Express', 'Chennai', 'Howrah', 1661, 55.0, 30.0, 'Tue-Sun', 'Officer V'),
(23, 'Mumbai Mail', 'Express', 'Chennai', 'Mumbai', 1273, 52.0, 26.1, 'Alt Days', 'Officer W'),
(24, 'Matsyagandha Express', 'Express', 'Mangalore', 'Mumbai', 894, 50.0, 15.0, 'Mon-Fri', 'Officer X'),
(25, 'Bangalore Mail', 'Superfast', 'Chennai', 'Bangalore', 362, 65.0, 5.5, 'Daily', 'Officer Y'),
(26, 'Ajmer Shatabdi', 'Superfast', 'New Delhi', 'Ajmer', 444, 85.0, 6.0, 'Mon-Sat', 'Officer Z'),
(27, 'Poorva Express', 'Express', 'Howrah', 'Delhi', 1447, 60.0, 24.2, 'Wed-Sat', 'Officer AA'),
(28, 'Kanchanjungha Express', 'Express', 'Sealdah', 'Agartala', 1505, 55.0, 30.0, 'Alt Days', 'Officer AB'),
(29, 'Vivek Express', 'Long Distance', 'Dibrugarh', 'Kanyakumari', 4219, 53.0, 79.0, 'Weekly', 'Officer AC'),
(30, 'Padmavati Express', 'Express', 'Secunderabad', 'Tirupati', 735, 70.0, 10.0, 'Daily', 'Officer AD');


CREATE TABLE school_info (
    school_id INT NOT NULL UNIQUE,
    school_name VARCHAR(100) NOT NULL UNIQUE,
    principal_name VARCHAR(50),
    board VARCHAR(30) NOT NULL,
    city VARCHAR(50),
    established_year INT,
    total_students INT,
    avg_pass_percent FLOAT,
    medium VARCHAR(20),
    approved_by VARCHAR(50)
);

INSERT INTO school_info VALUES
(1, 'Green Valley High School', 'Anjali Mehta', 'CBSE', 'Pune', 2005, 950, 94.3, 'English', 'State Board'),
(2, 'Riverdale Public School', 'Vikram Joshi', 'ICSE', 'Hyderabad', 2010, 820, 91.2, 'English', 'Central Board'),
(3, 'Sunrise Academy', 'Farida Khan', 'State', 'Bhopal', 1998, 1020, 88.5, 'Hindi', 'Education Dept'),
(4, 'Blue Bells School', 'Rakesh Kumar', 'CBSE', 'Delhi', 2002, 890, 92.1, 'English', 'State Board'),
(5, 'St. Thomas High', 'Mary Dsouza', 'ICSE', 'Mumbai', 1995, 770, 89.7, 'English', 'Central Board'),
(6, 'Hilltop International School', 'Sameer Naik', 'IB', 'Bangalore', 2015, 650, 95.5, 'English', 'IB Board'),
(7, 'Oakridge Global School', 'Neha Reddy', 'CBSE', 'Chennai', 2007, 880, 93.6, 'English', 'State Board'),
(8, 'Delhi Public School', 'Rajesh Verma', 'CBSE', 'Lucknow', 2001, 1000, 90.4, 'English', 'State Board'),
(9, 'Cambridge School', 'Shalini Nair', 'IGCSE', 'Kochi', 2012, 700, 94.9, 'English', 'IGCSE Board'),
(10, 'Loyola High School', 'Thomas Mathew', 'ICSE', 'Goa', 1990, 680, 88.3, 'English', 'Central Board'),
(11, 'New Horizon School', 'Sunita Shetty', 'State', 'Mangalore', 1997, 810, 86.7, 'Kannada', 'State Board'),
(12, 'St. Mary’s Convent', 'Sister Teresa', 'CBSE', 'Trichy', 2003, 720, 91.0, 'English', 'State Board'),
(13, 'Golden Future School', 'Ajay Singh', 'CBSE', 'Gurgaon', 2008, 950, 92.9, 'English', 'State Board'),
(14, 'National English School', 'Kavita Sharma', 'State', 'Jaipur', 1996, 780, 87.5, 'English', 'Education Dept'),
(15, 'Springfield High', 'Anand Raj', 'CBSE', 'Nagpur', 2000, 840, 89.4, 'English', 'State Board'),
(16, 'Bright Minds Academy', 'Pooja Ghosh', 'ICSE', 'Kolkata', 2004, 765, 90.7, 'English', 'Central Board'),
(17, 'Oxford Matric School', 'Ravi Chandran', 'State', 'Coimbatore', 1993, 730, 85.6, 'Tamil', 'State Board'),
(18, 'Indian Public School', 'Monica Jain', 'CBSE', 'Indore', 2011, 870, 91.8, 'English', 'State Board'),
(19, 'Silver Oak School', 'Daniel Francis', 'CBSE', 'Trivandrum', 2006, 690, 90.2, 'English', 'State Board'),
(20, 'Little Flower High School', 'Maria Paul', 'ICSE', 'Ranchi', 2000, 640, 89.0, 'English', 'Central Board'),
(21, 'Smart Scholars School', 'Imran Ali', 'CBSE', 'Surat', 2014, 820, 93.2, 'English', 'State Board'),
(22, 'Vishwa Bharati School', 'Gayathri Iyer', 'State', 'Patna', 2009, 760, 88.8, 'Hindi', 'Education Dept'),
(23, 'Heritage International', 'Amit Desai', 'IB', 'Ahmedabad', 2016, 670, 95.1, 'English', 'IB Board'),
(24, 'Gyan Mandir School', 'Sneha Agarwal', 'CBSE', 'Udaipur', 2005, 720, 91.5, 'English', 'State Board'),
(25, 'St. Xavier’s Academy', 'Peter Dsouza', 'ICSE', 'Vasai', 1994, 790, 90.1, 'English', 'Central Board'),
(26, 'Indian Heights School', 'Rohit Saxena', 'CBSE', 'Noida', 2006, 880, 92.4, 'English', 'State Board'),
(27, 'The Millennium School', 'Deepa Mehra', 'CBSE', 'Ghaziabad', 2007, 900, 91.3, 'English', 'State Board'),
(28, 'Sanskriti Vidyalaya', 'Narayan Murthy', 'State', 'Mysore', 1999, 750, 86.4, 'Kannada', 'Education Dept'),
(29, 'Blue Ridge School', 'Meenal Deshpande', 'ICSE', 'Pune', 2002, 810, 90.9, 'English', 'Central Board'),
(30, 'Galaxy Public School', 'Sushil Rao', 'CBSE', 'Delhi', 2010, 970, 94.0, 'English', 'State Board');


